config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  root 'sessions#new'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  get '/survey_admin/:id/dashboard', to: 'dashboards#survey_admin_dashboard', as: 'survey_admin_dashboard'
  get '/survey_taker/:id/dashboard', to: 'dashboards#survey_taker_dashboard', as: 'survey_taker_dashboard'

  resources :surveys do
    resources :questions
  end
  resources :questions do
  	resources :answers
  end
  resources :survey_responses

  namespace :api, defaults: { format: :json } do 
    namespace :v1 do 
      resources :surveys do 
        resources :questions
      end
    end 
  end 
end

app/models/question.rb
class Question < ApplicationRecord
	belongs_to :survey
	has_one :answer
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
	before_action :set_question, only: [:show, :edit, :update, :destroy]
	before_action :set_survey, only: [:show, :new, :create, :edit, :update, :destroy]

  def index
    @questions = Question.all
  end
  
  def show
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new(question_params)
    @question.survey_id = @survey.id

    respond_to do |format|
      if @question.save
        format.html { redirect_to survey_path(@survey), notice: 'Question was successfully created.' }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to survey_path(@survey), notice: 'Question was successfully updated.' }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to survey_path(@survey), notice: 'Question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  def set_question
    @question = Question.find(params[:id])
  end
  
  def set_survey
    @survey = Survey.find(params[:survey_id])
  end

  def question_params
    params.require(:question).permit(:title, :survey_id)
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.erb
<%= form_for [@survey, question] do |f| %>
  <div class="form-group">
    <div class="row">
      <div class="col">
        <%= f.text_field :title, autofocus: true, class: 'form-control', placeholder: "Title" %>
      </div>
    </div>        
  </div>
  <div class="text-center" style="margin-top: 15%;">
    <%= f.submit "Submit", class: "btn btn-primary btn-lg" %>
  </div>
<% end %>

app/views/questions/edit.html.erb
<!-- page content -->
<br><br>
<div class="container">
  <div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
  	  <div class="pull-left">
  	  	<%= link_to survey_admin_dashboard_path(current_user), title: "Back", data: { "toggle" => "tooltip", 'placement' => "top", turbolinks: false} do %>
	        <i class="fa fa-chevron-left" aria-hidden="true" style="font-size: 20px;"></i>
	      <% end %>
	    </div>            
			<h1 class="text-center">Update Question</h1><br>
			<%= render 'form', question: @question %>
    </div>
  </div>
</div>
<!-- /page content -->

app/views/questions/new.html.erb
<!-- page content -->
<br><br>
<div class="container">
  <div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
  	  <div class="pull-left">
  	  	<%= link_to survey_admin_dashboard_path(current_user), title: "Back", data: { "toggle" => "tooltip", 'placement' => "top", turbolinks: false} do %>
	        <i class="fa fa-chevron-left" aria-hidden="true" style="font-size: 20px;"></i>
	      <% end %>
	    </div>            
			<h1 class="text-center">Create Question</h1><br>
			<%= render 'form', question: @question %>
    </div>
  </div>
</div>
<!-- /page content -->