config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  root 'sessions#new'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  get '/survey_admin/:id/dashboard', to: 'dashboards#survey_admin_dashboard', as: 'survey_admin_dashboard'
  get '/survey_taker/:id/dashboard', to: 'dashboards#survey_taker_dashboard', as: 'survey_taker_dashboard'

  resources :surveys do
    resources :questions
  end
  resources :questions do
  	resources :answers
  end
  resources :survey_responses

  namespace :api, defaults: { format: :json } do 
    namespace :v1 do 
      resources :surveys do 
        resources :questions
      end
    end 
  end 
end

app/models/survey.rb
class Survey < ApplicationRecord
	has_many :questions
	has_many :survey_responses

	enum status: [:active, :inactive]
	accepts_nested_attributes_for :questions, :survey_responses
end

app/controllers/api/v1/surveys_controller.rb
class Api::V1::SurveysController < ApiController
	before_action :set_survey, only: [:show, :update, :destroy]
	skip_before_action :authenticate_user, only: [:index, :show]

  def index
    @surveys = Survey.where(status: :active)
    render json: @surveys.to_json(:include => [:survey_responses, questions: {include: [:answer]}])
  end
  
  def show
  	render json: @survey
  end

  def create
    @survey = Survey.new(survey_params)

    if @survey.save
      render json: @survey, status: :created, location: @survey
    else
      render json: @survey.errors, status: :unprocessable_entity
    end
  end

  def update
    if @survey.update(survey_params)
      render json: @survey, status: :ok, location: @survey
    else
      render json: @survey.errors, status: :unprocessable_entity
    end
  end

  def destroy
    @survey.destroy
  end

  private
  def set_survey
    @survey = Survey.find(params[:id])
  end

  def survey_params
    params.permit(:title, :status)
  end
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
	before_action :set_survey, only: [:show, :edit, :update, :destroy]

  def index
    @surveys = Survey.all
  end
  
  def show
  end

  def new
    @survey = Survey.new
  end

  def create
    @survey = Survey.new(survey_params)

    respond_to do |format|
      if @survey.save
        format.html { redirect_to survey_admin_dashboard_path(current_user), notice: 'Survey was successfully created.' }
        format.json { render :show, status: :created, location: @survey }
      else
        format.html { render :new }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @survey.update(survey_params)
        format.html { redirect_to survey_admin_dashboard_path(current_user), notice: 'Survey was successfully updated.' }
        format.json { render :show, status: :ok, location: @survey }
      else
        format.html { render :edit }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @survey.destroy
    respond_to do |format|
      format.html { redirect_to survey_admin_dashboard_path(current_user), notice: 'Survey was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  def set_survey
    @survey = Survey.find(params[:id])
  end

  def survey_params
    params.require(:survey).permit(:title, :status)
  end
end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/views/surveys/_form.html.erb
<%= form_for(survey) do |f| %>
  <div class="form-group">
    <div class="row">
      <div class="col">
        <%= f.text_field :title, autofocus: true, class: 'form-control', placeholder: "Title" %>
      </div>
      <div class="col">
      	<%= f.select :status, Survey.statuses.map { |key, value| [key.humanize, key] }, { include_blank: true }, class: 'form-control', style:"width:100%;" %>
      </div>
    </div>        
  </div>
  <div class="text-center" style="margin-top: 15%;">
    <%= f.submit "Submit", class: "btn btn-primary btn-lg" %>
  </div>
<% end %>

app/views/surveys/edit.html.erb
<!-- page content -->
<br><br>
<div class="container">
  <div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
  	  <div class="pull-left">
  	  	<%= link_to survey_admin_dashboard_path(current_user), title: "Back", data: { "toggle" => "tooltip", 'placement' => "top", turbolinks: false} do %>
	        <i class="fa fa-chevron-left" aria-hidden="true" style="font-size: 20px;"></i>
	      <% end %>
	    </div>            
			<h1 class="text-center">Update Survey</h1><br>
			<%= render 'form', survey: @survey %>
    </div>
  </div>
</div>
<!-- /page content -->

app/views/surveys/new.html.erb
<!-- page content -->
<br><br>
<div class="container">
  <div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
  	  <div class="pull-left">
  	  	<%= link_to survey_admin_dashboard_path(current_user), title: "Back", data: { "toggle" => "tooltip", 'placement' => "top", turbolinks: false} do %>
	        <i class="fa fa-chevron-left" aria-hidden="true" style="font-size: 20px;"></i>
	      <% end %>
	    </div>            
			<h1 class="text-center">Create Survey</h1><br>
			<%= render 'form', survey: @survey %>
    </div>
  </div>
</div>
<!-- /page content -->

app/views/surveys/show.html.erb
<br><br>
<div class="container">
	<table style="width:100%" border="2">
	  <thead>
	    <tr>
	      <th>Title</th>
	      <th>Status</th>
	      <th>Actions</th>
	    </tr>
	  </thead>

	  <tbody>
	    <tr>
	      <td><%= @survey.title %></td>
	      <td><%= @survey.status.titleize %></td>
	      <td>
	        <%= link_to "Edit Survey", edit_survey_path(@survey), class: "btn btn-primary btn-sm" %>&nbsp;&nbsp;
	        <%= link_to "Delete Survey", survey_path(@survey), method: :delete, data: { confirm: 'Are you sure?'}, class: "btn btn-primary btn-sm" %>
	      </td>
	    </tr>
	  </tbody>
	</table>
  <br>
  <h3 class="text-center">Questions</h3>
  <div class="pull-left">
  	<%= link_to "Add new question", new_survey_question_path(@survey), class: "btn btn-primary btn-sm" %>
  </div>
  <table style="width:100%" border="2">
	  <thead>
	    <tr>
	      <th>Title</th>
	      <th>Actions</th>
	    </tr>
	  </thead>

	  <tbody>
    	<% @survey.questions.each do |question| %>
    	  <tr>
		      <td><%= question.title %></td>
		      <td>
		        <%= link_to "Edit Question", edit_survey_question_path(@survey, question), class: "btn btn-primary btn-sm" %>&nbsp;&nbsp;
		        <%= link_to "Delete Question", survey_question_path(@survey, question), method: :delete, data: { confirm: 'Are you sure?'}, class: "btn btn-primary btn-sm" %>
		      </td>
	      </tr>
	    <% end %>
	  </tbody>
	</table>
  <br>
  <h3 class="text-center">Survey Responses</h3>
  <table style="width:100%" border="2">
	  <thead>
	    <tr>
	      <th>Rating</th>
	      <th>Feedback</th>
	      <th>Given By</th>
	    </tr>
	  </thead>

	  <tbody>
    	<% @survey.survey_responses.each do |sr| %>
    	  <tr>
		      <td><%= sr.rating.humanize.titleize %></td>
		      <td><%= sr.feedback %></td>
		      <td><%= sr.feedback_given_by %></td>
	      </tr>
	    <% end %>
	  </tbody>
	</table>
  <br>
	<div class="pull-left">
		<%= link_to survey_admin_dashboard_path(current_user), title: "Back", data: { "toggle" => "tooltip", 'placement' => "top", turbolinks: false} do %>
		  <i class="fa fa-chevron-left" aria-hidden="true" style="font-size: 20px;"></i>
		<% end %>
	</div>
</div>