config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  root 'sessions#new'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  get '/survey_admin/:id/dashboard', to: 'dashboards#survey_admin_dashboard', as: 'survey_admin_dashboard'
  get '/survey_taker/:id/dashboard', to: 'dashboards#survey_taker_dashboard', as: 'survey_taker_dashboard'

  resources :surveys do
    resources :questions
  end
  resources :questions do
  	resources :answers
  end
  resources :survey_responses

  namespace :api, defaults: { format: :json } do 
    namespace :v1 do 
      resources :surveys do 
        resources :questions
      end
    end 
  end 
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
	before_action :set_surveys

	def survey_admin_dashboard
	end

	def survey_taker_dashboard
		@answer = Answer.new
	end

	private
	def set_surveys
		@surveys = Survey.where(status: :active)
	end
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/views/dashboards/survey_admin_dashboard.html.erb
<!-- page content -->
 <br><br>
<div class="container">
  <div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
    	<div class="pull-left">
        <%= link_to new_survey_path, class: "btn btn-primary" do %>
          <i class="fa fa-plus" aria-hidden="true" style="font-size: 20px;"></i> Add new survey
        <% end %>
      </div>
      <br>
    
      <h1 style="margin-left: 40%;">List Of Active Surveys</h1>
      <table style="width:100%" border="2">
        <thead>
          <tr>
            <th>Title</th>
            <th>Status</th>
            <th>Actions</th>
          </tr>
        </thead>

        <tbody>
          <% @surveys.each do |survey| %>
            <tr>
              <td><%= survey.title %></td>
              <td><%= survey.status.titleize %></td>
              <td>
                <%= link_to "View Survey", survey_path(survey), class: "btn btn-primary btn-sm" %>&nbsp;&nbsp;
                <%= link_to "Edit Survey", edit_survey_path(survey), class: "btn btn-primary btn-sm" %>&nbsp;&nbsp;
                <%= link_to "Delete Survey", survey_path(survey), method: :delete, data: { confirm: 'Are you sure?'}, class: "btn btn-primary btn-sm" %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/dashboards/survey_taker_dashboard.html.erb
<br><br>
<div class="container">
	<% @surveys.each do |survey| %>
	  <strong><%= survey.title %></strong><br>

	  Questions:<br>
    <% survey.questions.each_with_index do |question,index| %>
	    <ul>
	    	<li><%= question.title%></li>&nbsp;&nbsp;
	    	<div class="answer">
		    	<%= link_to '#', data: { turbolinks: false}, class: "btn btn-primary btn-sm" do %>
	          Answer this question
	        <% end %>
	        <%= hidden_field_tag "question", question.id, class: "question" %>
	      </div>
	      <br>
        <div class="answer-form-<%=question.id%> hide">
        	<%= form_for [question, @answer], remote: true do |f| %>
        	  <div class="form-group">
					    <div class="row">
					      <div class="col">
					        <%= f.text_area :content, autofocus: true, class: 'form-control', placeholder: "Write your answer", required: true %>
					        <%= f.hidden_field :answered_by, value: current_user.full_name %>
					      </div>
					    </div>        
					  </div>
					  <div class="text-center" style="margin-top: 2%;">
					    <%= f.submit "Submit", class: "btn btn-primary btn-sm" %>
					  </div>
					<% end %>
				</div>
      </ul>
    <% end %>
  <% end %>
</div>

<style type="text/css">
	.hide{
    display: none;
}
</style>

<script type="text/javascript">
	
		$(".answer").each(function(index){
			$(this).on("click",function(){
				var question_id = $(this).find(".question").val()
        $(".answer-form-"+question_id).toggle();
			})
		})
</script>